sudo: required
services:
  - docker

before_install:
  - docker build -t unusualcaspento/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true unusualcaspento/frontend npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-091956232112"
  bucket_path: "docker"
  on:
    branch: main