FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .
#^^Takes the all folders ("Public", "src") and copys them into the `WORKDIR "/app"` directory
CMD ["npm", "run", "start"]

## We us this file to run a travis test suite